theme: jekyll-theme-cayman
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Denoising Depth Images from RGB
description: ECE M202A/CSM213A Project Fall 2023
